-- 코드를 작성해주세요
SELECT I.ITEM_ID, I.ITEM_NAME
FROM ITEM_INFO I JOIN ITEM_TREE T
ON I.ITEM_ID = T.ITEM_ID
WHERE I.ITEM_ID IN (SELECT ITEM_ID FROM ITEM_TREE WHERE ISNULL(PARENT_ITEM_ID))
ORDER BY I.ITEM_ID ASC;