-- 코드를 작성해주세요
-- ITEM_INFO : ITEM_ID, ITEM_NAME, RARITY, PRICE
-- ITEM_TREE : ITEM_ID, PARENT_ITEM_ID

SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
WHERE PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY ITEM_ID DESC;